In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-06-17 08:00:53.584685: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
#sentences
sent=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good",
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
#define the vocabulary size
voc_size=10000

In [8]:
# One hot represesntation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6338, 8722, 4628, 2700],
 [6338, 8722, 4628, 7657],
 [6338, 6194, 4628, 985],
 [8378, 3004, 1038, 6303, 3603],
 [8378, 3004, 1038, 6303, 7094],
 [3040, 6338, 7672, 4628, 5755],
 [6676, 9840, 8907, 6303]]

In [9]:
#word embedding representation
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6338 8722 4628 2700]
 [   0    0    0    0 6338 8722 4628 7657]
 [   0    0    0    0 6338 6194 4628  985]
 [   0    0    0 8378 3004 1038 6303 3603]
 [   0    0    0 8378 3004 1038 6303 7094]
 [   0    0    0 3040 6338 7672 4628 5755]
 [   0    0    0    0 6676 9840 8907 6303]]


In [13]:
#feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mse")

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 265ms/step


array([[[ 1.6079117e-02,  3.1462524e-02,  1.7341521e-02, -2.8377771e-03,
         -4.3213870e-02,  4.6556715e-02,  4.3554511e-02, -4.9530126e-02,
         -1.7643653e-02, -3.3028163e-02],
        [ 1.6079117e-02,  3.1462524e-02,  1.7341521e-02, -2.8377771e-03,
         -4.3213870e-02,  4.6556715e-02,  4.3554511e-02, -4.9530126e-02,
         -1.7643653e-02, -3.3028163e-02],
        [ 1.6079117e-02,  3.1462524e-02,  1.7341521e-02, -2.8377771e-03,
         -4.3213870e-02,  4.6556715e-02,  4.3554511e-02, -4.9530126e-02,
         -1.7643653e-02, -3.3028163e-02],
        [ 1.6079117e-02,  3.1462524e-02,  1.7341521e-02, -2.8377771e-03,
         -4.3213870e-02,  4.6556715e-02,  4.3554511e-02, -4.9530126e-02,
         -1.7643653e-02, -3.3028163e-02],
        [-2.1106815e-02,  1.7347708e-03, -1.0108553e-02, -4.6193946e-02,
         -3.1677533e-02,  2.8794181e-02, -1.6999565e-02,  1.9292179e-02,
         -2.0048261e-02,  2.9832032e-02],
        [ 1.2511004e-02,  4.4455614e-02,  4.5283441e-02, -3.